### ISSUE TITLE
Error on dynamic routes (SSR)

### ISSUE THREAD

**Issue by wroughtec** [krychaxp/nextjs-google-fonts#3]
When loading the app on a static page everything works normally and if I navigate to a dynamically rendered url then this works with no issues. However If I refresh the page I get shown a 404 page and on the network tab I see a 500 error for the document (this is only on a production build).

Some further digging looks like it is caused by the stylesheet being added to the head:
```
{"message":">>>> [ '/fonts/style/Noto.css' ]","timestamp":"2021-05-16T10:13:17.092Z","type":"out","process_id":0,"app_name":"appName"}
{"message":"TypeError: Cannot assign to read only property 'children' of object '#<Object>'    at /.next/server/pages/_document.js:679:29    at /node_modules/react/cjs/react.development.js:1067:17    at mapIntoArray (/node_modules/react/cjs/react.development.js:964:23)    at mapIntoArray (/node_modules/react/cjs/react.development.js:1004:23)    at Object.mapChildren [as map] (/node_modules/react/cjs/react.development.js:1066:3)    at Head.makeStylesheetInert (/.next/server/pages/_document.js:670:36)    at /.next/server/pages/_document.js:679:36    at /node_modules/react/cjs/react.development.js:1067:17    at mapIntoArray (/node_modules/react/cjs/react.development.js:964:23)    at mapIntoArray (/node_modules/react/cjs/react.development.js:1004:23)","timestamp":"2021-05-16T10:13:17.095Z","type":"err","process_id":0,"app_name":"appName"}
```

The offending compiled code being (console log added to the compiled code post build) in _document.js `/.next/server/pages/_document.js`:
```
makeStylesheetInert(node) {
    return _react.default.Children.map(node, c => {
      if (c.type === 'link' && c.props['href'] && _constants.OPTIMIZED_FONT_PROVIDERS.some(url => c.props['href'].startsWith(url))) {
        const newProps = _objectSpread({}, c.props || {});

        newProps['data-href'] = newProps['href'];
        newProps['href'] = undefined;
        return /*#__PURE__*/_react.default.cloneElement(c, newProps);
      } else if (c.props && c.props['children']) {
        console.log('>>>>', c.props['children'])
        c.props['children'] = this.makeStylesheetInert(c.props['children']);
      }

      return c;
    });
  }
```
The error occurring below the console log line. When the `GoogleFonts()` is removed from _document then there are no issues.

Below is my custom _document page:

```
import Document, { Html, Head, Main, NextScript, DocumentContext } from 'next/document';
import { ServerStyleSheets } from '@material-ui/core/styles';
import { materialTheme as theme } from '@acre-fe/theme';
import { GoogleFonts } from 'nextjs-google-fonts/GoogleFonts';
import { Children, ReactElement } from 'react';

export default class MyDocument extends Document<ReactElement> {
  static async getInitialProps(ctx: DocumentContext) {
    // Resolution order
    //
    // On the server:
    // 1. app.getInitialProps
    // 2. page.getInitialProps
    // 3. document.getInitialProps
    // 4. app.render
    // 5. page.render
    // 6. document.render
    //
    // On the server with error:
    // 1. document.getInitialProps
    // 2. app.render
    // 3. page.render
    // 4. document.render
    //
    // On the client
    // 1. app.getInitialProps
    // 2. page.getInitialProps
    // 3. app.render
    // 4. page.render

    // Render app and page and get the context of the page with collected side effects.
    const sheets = new ServerStyleSheets();
    const originalRenderPage = ctx.renderPage;

    ctx.renderPage = () =>
      originalRenderPage({
        enhanceApp: (App) => (props) => sheets.collect(<App {...props} />)
      });

    const initialProps = await Document.getInitialProps(ctx);

    return {
      ...initialProps,
      // Styles fragment is rendered after the app and page rendering finish.
      styles: [...Children.toArray(initialProps.styles), sheets.getStyleElement()]
    };
  }

  render(): ReactElement {
    return (
      <Html lang="en">
        <Head>
          {/* PWA primary color */}
          <meta name="theme-color" content={theme.palette.primary.main} />
          <link
            rel="preload"
            as="font"
            type="font/woff2"
            crossOrigin="anonymous"
            href="/fonts/NBInternationalPro/NBInternationalPro-Lig-kern-latin.woff2"
          />
          <link
            rel="preload"
            as="font"
            type="font/woff2"
            crossOrigin="anonymous"
            href="/fonts/NBInternationalPro/NBInternationalPro-Reg-kern-latin.woff2"
          />
          <link
            rel="preload"
            as="font"
            type="font/woff2"
            crossOrigin="anonymous"
            href="/fonts/NBInternationalPro/NBInternationalPro-Bol-kern-latin.woff2"
          />
          {GoogleFonts()}
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
```
So I am not doing anything too crazy

**Comment by krychaxp** [comment]
What URL you add in next.config.js ?

**Comment by wroughtec** [comment]
```
const googleFonts = withGoogleFonts({
  googleFonts: {
    fonts: ['https://fonts.googleapis.com/css2?family=Noto+Serif:wght@400;700&display=swap']
  }
});
```

**Comment by krychaxp** [comment]
_document is .js or .ts ?

**Comment by wroughtec** [comment]
typescript

**Comment by wroughtec** [comment]
also tried it with `https://fonts.googleapis.com/css?family=Noto+Serif:400,700&display=swap` (which has inlined style) same result

**Comment by krychaxp** [comment]
check this `_document.js`
```
import Document, { Html, Head, Main, NextScript } from "next/document";
import { ServerStyleSheets } from "@material-ui/core/styles";
import { GoogleFonts } from "nextjs-google-fonts/GoogleFonts";

export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const sheets = new ServerStyleSheets();
    const originalRenderPage = ctx.renderPage;

    ctx.renderPage = () =>
      originalRenderPage({
        enhanceApp: (App) => (props) => sheets.collect(<App {...props} />),
      });

    const initialProps = await Document.getInitialProps(ctx);

    return {
      ...initialProps,
      styles: [initialProps.styles, sheets.getStyleElement()],
    };
  }

  render() {
    return (
      <Html lang="en">
        <Head>{GoogleFonts()}</Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
```

**Comment by wroughtec** [comment]
same error unfortunately

**Comment by wroughtec** [comment]
Even tried removing the whole of the get initial props stuff.

When I hack the plugin to return just the object and handle it my side ie create the links etc. in the _document file then it works

**Comment by krychaxp** [comment]
can you paste all console text from `npm run dev` ?

**Comment by wroughtec** [comment]
```
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /.env.local
info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
> [nextjs-google-fonts] (Prevent download again) - Fonts have been already saved
info  - automatically enabled Fast Refresh for 1 custom loader
info  - Using external babel configuration from /.babelrc
Webpack Bundle Analyzer saved report to /.next/analyze/client.html
Webpack Bundle Analyzer saved report to /.next/analyze/server.html
event - compiled successfully
event - build page: /deals/[dealRef]
wait  - compiling...
Webpack Bundle Analyzer saved report to /.next/analyze/client.html
Webpack Bundle Analyzer saved report to /.next/analyze/server.html
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - build page: /next/dist/pages/_error
event - build page: /next/dist/pages/_error
Webpack Bundle Analyzer saved report to /.next/analyze/server.html
Webpack Bundle Analyzer saved report to /.next/analyze/client.html
react-i18next:: You will need to pass in an i18next instance by using initReactI18next
Webpack Bundle Analyzer saved report to /.next/analyze/server.html
event - compiled successfully
Webpack Bundle Analyzer saved report to /.next/analyze/client.html
```

No errors show on dev and page displays as it should

**Comment by krychaxp** [comment]
it is interesting, because I try this code:

> check this `_document.js`
> 
> ```
> import Document, { Html, Head, Main, NextScript } from "next/document";
> import { ServerStyleSheets } from "@material-ui/core/styles";
> import { GoogleFonts } from "nextjs-google-fonts/GoogleFonts";
> 
> export default class MyDocument extends Document {
>   static async getInitialProps(ctx) {
>     const sheets = new ServerStyleSheets();
>     const originalRenderPage = ctx.renderPage;
> 
>     ctx.renderPage = () =>
>       originalRenderPage({
>         enhanceApp: (App) => (props) => sheets.collect(<App {...props} />),
>       });
> 
>     const initialProps = await Document.getInitialProps(ctx);
> 
>     return {
>       ...initialProps,
>       styles: [initialProps.styles, sheets.getStyleElement()],
>     };
>   }
> 
>   render() {
>     return (
>       <Html lang="en">
>         <Head>{GoogleFonts()}</Head>
>         <body>
>           <Main />
>           <NextScript />
>         </body>
>       </Html>
>     );
>   }
> }
> ```

and it works on `npm run dev` and `npm run build` 🤔🤔

**Comment by wroughtec** [comment]
weird hmm I might just patch for now as may be something further down field is causing the issue

**Comment by krychaxp** [comment]
which version of package do you use?

**Comment by wroughtec** [comment]
`3.3.2`

**Comment by krychaxp** [comment]
This is some interesting
> ```
> {"message":">>>> [ '/fonts/style/Noto.css' ]","timestamp":"2021-05-16T10:13:17.092Z","type":"out","process_id":0,"app_name":"appName"}
> {"message":"TypeError: Cannot assign to read only property 'children' of object '#<Object>'    at /.next/server/pages/_document.js:679:29    at /node_modules/react/cjs/react.development.js:1067:17    at mapIntoArray (/node_modules/react/cjs/react.development.js:964:23)    at mapIntoArray (/node_modules/react/cjs/react.development.js:1004:23)    at Object.mapChildren [as map] (/node_modules/react/cjs/react.development.js:1066:3)    at Head.makeStylesheetInert (/.next/server/pages/_document.js:670:36)    at /.next/server/pages/_document.js:679:36    at /node_modules/react/cjs/react.development.js:1067:17    at mapIntoArray (/node_modules/react/cjs/react.development.js:964:23)    at mapIntoArray (/node_modules/react/cjs/react.development.js:1004:23)","timestamp":"2021-05-16T10:13:17.095Z","type":"err","process_id":0,"app_name":"appName"}
> ```

because now te css code is add inline in <style> tag in head, not importing css code from file by url - `/fonts/style/Noto.css` 🤔.
Are you/can you trying reinstall package and delete 'fonts' folder in your app?

**Comment by wroughtec** [comment]
Sorry got side tracked by other things.

The css vs style issue was down to the url from google had selected one which gave a css file so that console log was from that when I used the correct url with the inlined styles then it was string of styles but alas still got the same error. I suspect something somewhere else is conflicting and causing the issue. I will probably pick it up sometime next week so if I find a solution will let you know.
